apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: iris:0.1.1
          imagePullPolicy: Never
          ports:
            - containerPort: 1080

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 1080
    protocol: TCP
    targetPort: 1080
  selector:
    app: flaskapi
  type: LoadBalancer
